### ISSUE TITLE
Balanced JS lib on Parse.com platform

### ISSUE THREAD

**Issue by sidharthshah** [balanced/balanced-node#29]
Hello, 
I am developing a Parse app, which requires payment integration. Unfortunately Parse.com doesn't support NPM, because of which I cannot do npm install and get work done. Is there a way to include say a "stand alone" js library which includes all dependencies. Right now its not working because jsonapi-client.js (one of Balanced.js's dependencies) is found to be missing.

Error: https://gist.github.com/sidharthshah/8a44fce5c8b5bd2c82cb

Any other suggestion would be appreciated.

PS: This is a cross post from https://github.com/balanced/balanced-js/issues/93

**Comment by matthewfl** [comment]
Hi @sidharthshah, I am assuming that getting this client to work on a platform that doesn't suppose npm is largely driven by getting [jsonapi client](https://github.com/matthewfl/jsonapi-node) working.

Assuming that you can upload files, and it follows the same loading structure as node, then it would likely be easiest to simply preform npm install of the balanced-node directory, and then package it along with the node_modules directory that is generated.  

Here is an alternate approach however I have not tried this:
1. jsonapi-client is largely in a single file, so it shouldn't be that hard to isolate out of npm
   (https://github.com/matthewfl/jsonapi-node/blob/master/lib.js)
2. the first dependency of jsonapi-cleint is Q, which is also a single file (https://github.com/kriskowal/q/blob/v1/q.js)
3. the hardest one to isolate out of npm is requests, which has something like 25+ dependencies.  Instead of trying to package this, I would try and substitute it with another library to make network requests (possibly provided by parse).  The jsonapi-client only interfaces with it [here](https://github.com/matthewfl/jsonapi-node/blob/master/lib.js#L84) and it only uses small subset of features.  Basically, you will get an object with a url, method, json, and headers, and a callback where you return the result.
